version: '3.8'

services:
  web:
    image: nginx:latest
    environment:
      ENVIRONMENT: "production"
      DEBUG: "false"
      DB_HOST: "db.example.com"
      DB_PORT: "5432"
    ports:
      - "80:80"
